backend = "xrender";
vsync = true;

# скругление окон
corner-radius = 20;

# исключения (чтобы не ломать панели/доки)
rounded-corners-exclude = [
  "class_g = 'Conky'",
  "class_g = 'polybar'",
  "window_type = 'dock'",
  "window_type = 'desktop'"
];

# отключаем всё лишнее
shadow = false;
fading = false;
inactive-opacity = 1.0;
active-opacity = 1.0;
frame-opacity = 1.0;
