#################################################################################################
########################                                                 ########################
########################               Window Settings                   ########################
########################                                                 ########################
#################################################################################################

for_window                       [all] border pixel 0
for_window                       [title="(?i)Friends List"] floating enable, move position center
for_window                       [title="(?i)Steam - News"] floating enable, move position center
for_window                       [title="(?i)Просмотр медиа"] floating enable, move position center
for_window                       [class="Navigator"] floating enable, move position center

for_window                       [class="discord"] move workspace 2
for_window                       [class="Spotify"] move workspace 3

for_window [class="Conky"] floating enable
for_window [class="Conky"] border none
for_window [class="Conky"] move position center
for_window [class="Conky"] focus disable
for_window [class="Conky"] sticky enable
