; [color]
;
; background = #242933
; foreground = #BBC3D4
; sep = #E5E9F0
;
; white = #ECEFF4
; black = #2E3440
; red = #BF616A
; green = #A3BE8C
; yellow = #EBCB8B
; blue = #5E81AC
; purple = #B48EAD
; cyan = #8FBCBB
; pink = #C5727A
; orange = #D08770

[color]
background = #2D353B
foreground = #D3C6AA
sep = #859289
white = #D3C6AA
black = #2D353B
red = #E67E80
green = #A7C080
yellow = #DBBC7F
blue = #7FBBB3
purple = #D699B6
cyan = #83C092
pink = #D699B6
orange = #E69875
